# create data lists
# data_btss = list(
#   "mbo_lambda0.5" = readRDS("data/BTSS/mbo_lambda0.5.rds"),
#   "mbo_lambda1" = readRDS("data/BTSS/mbo_lambda1.rds"),
#   "mbo_lambda2" = readRDS("data/BTSS/mbo_lambda2.rds"),
#   "test" = readRDS("data/BTSS/randomLHS_1000.rds")
# )
# 
# data_kc1 = list(
#   "mbo_lambda0.5" = readRDS("data/kc1/mbo_lambda0.5.rds"),
#   "mbo_lambda1" = readRDS("data/kc1/mbo_lambda1.rds"),
#   "mbo_lambda2" = readRDS("data/kc1/mbo_lambda2.rds"),
#   "test" = readRDS("data/kc1/randomLHS_1000.rds")
# )




folder = list.files("data/")
folder = folder[-which(folder == "data.RData")]
folder = folder[-which(folder == "numerai28.6")]

for (i in folder) {
  data = readRDS(paste0("data/",i, "/mlrmbo_30_repls.rds"))
  data.list = list(
    "mbo_lambda0.5" = data$result[1:30],
    "mbo_lambda1" = data$result[31:60],
    "mbo_lambda2" = data$result[61:90],
    "test" = data$result[91]
    
    
  )
  assign(paste0("data_", tolower(i)), data.list)
  
}




get_objects <- function(data, lambda, iteration){
  objectname = paste0("mbo_lambda", lambda)
  object = data[[objectname]][[iteration]]$res
  model = object$models[[2]]
  model.best = object$models[[1]]
  test.holdout = object$opt.path$env$path[-(1:object$best.ind),]
  data.train = object$opt.path$env$path
  data.test = data$test[[1]]$res$opt.path$env$path
  return(list("model" = model, "data_train" = data.train, "data_test" = data.test 
              ,"model_best" = model.best, "test_holdout" = test.holdout
              ))
}


#test = get_objects(data = data_btss, lambda = 0.5)
# test = get_objects(data_btss, 1, 1)
# 
# 
# 
# 
# best.params = readRDS("../moc/saved_objects/best_configs.rds")  # generated by irace in folder appendix_irace
# USE_TRAINED_MODEL = TRUE
# PARALLEL = TRUE
# 
# x.interest = test$data_train[200,]
# data = test$data_train[-200,]
# 
# pred = Predictor$new(model = test$model, data = data,
#                      conditional = FALSE)
# ctr = partykit::ctree_control(maxdepth = 5L)
# 
# set.seed(1234)
# pred$conditionals = fit_conditionals(pred$data$get.x(), ctrl = ctr)
# 
# ###---- Compute counterfactuals ----
# prediction = pred$predict(x.interest)$.prediction
# 
# set.seed(1000)
# credit.cf = Counterfactuals$new(predictor = pred, x.interest = x.interest,
#                                 target = c(min(data$y), prediction+0.05*prediction),
#                                 epsilon = 0, generations = list(mosmafs::mosmafsTermStagnationHV(10),
#                                 mosmafs::mosmafsTermGenerations(200)),
#                                 # mu = best.params$mu,
#                                 # p.mut = best.params$p.mut, p.rec = best.params$p.rec,
#                                 # p.mut.gen = best.params$p.mut.gen,
#                                 # p.mut.use.orig = best.params$p.mut.use.orig,
#                                 # p.rec.gen = best.params$p.rec.gen,
#                                 initialization = "icecurve"#,
#                                 # p.rec.use.orig = best.params$p.rec.use.orig
#                                 )
# 
# # Number of counterfactuals
# nrow(credit.cf$results$counterfactuals)
# id = credit.cf$results$counterfactuals$dist.target < 0.01
# sum(id)
# 
# # Focus counterfactuals that met target
# credit.cf$results$counterfactuals = credit.cf$results$counterfactuals[which(id), ]
# credit.cf$results$counterfactuals.diff = credit.cf$results$counterfactuals.diff[which(id), ]
# 
# # Get relative frequency of feature changes
# credit.cf$get_frequency()
# 
# 
# ###---- Plots ----
# a = credit.cf$plot_parallel(features = c("lambda", "colsample_bytree", "max_depth"), plot.x.interest = TRUE)
# a = a + scale_x_discrete(expand = c(0.1, 0.1), labels= c("lambda", "colsample_bytree", "max_depth"))
# a
# b = credit.cf$plot_surface(features = c("lambda", "colsample_bytree"))
# b
# c = credit.cf$plot_hv()
# c
